export default actionsType = {
  USER_SET_CURRENT_USER_DATA:"USER_SET_CURRENT_USER_DATA",
  USER_SET_UPDATE_USER_DATA: "USER_SET_UPDATE_USER_DATA",
  SAGA_USER_LOGIN:"SAGA_USER_LOGIN",
  SAGA_USERS_GET: "SAGA_USERS_GET",
  SIGN_UP: 'SIGN_UP',
  DELETE_USER: 'DELETE_USER',
  LOAD_DATA: "LOAD_DATA",
  SET_DATA: 'SET_DATA',
  SIGN_IN: 'SIGN_IN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  LOAD_NEWS: 'LOAD_NEWS',
  RENDER_NEWS: 'RENDER_NEWS'
}