export default actionsType = {
  USER_SET_CURRENT_USER_DATA:"USER_SET_CURRENT_USER_DATA",
  USER_SET_UPDATE_USER_DATA: "USER_SET_UPDATE_USER_DATA",
  SAGA_USER_LOGIN:"SAGA_USER_LOGIN",
  SAGA_USERS_GET: "SAGA_USERS_GET",



}